### ISSUE TITLE
convert to static site

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/tools#133]
**Todo**
- [ ] host the site on GitHub pages
- [ ] each page should be a standalone tool
- [ ] pages will share a common page template (written in Handlebars)
- [ ] the build process should be shared across tools (each tool gets built in the same way)
  - [ ] compile HTML (using Handlebars)
  - [ ] convert LESS > CSS
  - [ ] transpile JS
- [ ] delete the Tools web app on Azure

**Questions**
- Can you avoid having to type / use the `.html` extension by naming each page's main HTML file `index.html`?
